version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          name: Restore ~/.npm
          key: dotnpm-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: node -v && npm -v
      - run: npm ci
      - save_cache:
          name: Cache ~/.npm
          key: dotnpm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Install reviewdog
          command: curl --silent --fail --location https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
      - run:
          name: textlint
          command: npm run textlint -- ./*.md
